repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '^.+?\.json.+?\.ya?ml$'
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-print==5.0.0'
        ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.16.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
  - repo: https://github.com/python/black
    rev: 24.10
    hooks:
      - id: black
        additional_dependencies: [
          'click>=8.0.4'
        ]